# Generated by Django 4.1.7 on 2023-05-15 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dms", "0003_dmroom_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dm",
            old_name="user",
            new_name="member",
        ),
        migrations.RemoveField(
            model_name="dmroom",
            name="users",
        ),
        migrations.AddField(
            model_name="dmroom",
            name="host",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hosted_dmroom",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dmroom",
            name="members",
            field=models.ManyToManyField(
                related_name="joined_dmroom", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
