# Generated by Django 4.1.7 on 2023-05-15 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dms", "0004_rename_user_dm_member_remove_dmroom_users_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dmroom",
            name="host",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hosted_dmrooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dmroom",
            name="members",
            field=models.ManyToManyField(
                related_name="joined_dmrooms", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
