# Generated by Django 4.1.7 on 2023-06-14 10:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dms", "0005_alter_dmroom_host_alter_dmroom_members"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dm",
            options={"ordering": ["-created_at"], "verbose_name": "Direct Message"},
        ),
        migrations.AlterModelOptions(
            name="dmroom",
            options={"ordering": ["-created_at"], "verbose_name": "Chatting Room"},
        ),
    ]
