# Generated by Django 4.1.7 on 2023-05-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video",
            field=models.URLField(),
        ),
    ]
