# Generated by Django 4.1.7 on 2023-05-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dms", "0004_rename_user_dm_member_remove_dmroom_users_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dmrooms",
            field=models.ManyToManyField(related_name="member", to="dms.dmroom"),
        ),
    ]
