# Generated by Django 4.1.7 on 2023-06-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_following"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_photo",
            field=models.URLField(default="", null=True, verbose_name="프로필 사진"),
        ),
    ]
