# Generated by Django 4.1.7 on 2023-08-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_photo",
            field=models.URLField(null=True, verbose_name="프로필 사진"),
        ),
    ]
