# Generated by Django 4.1.7 on 2023-03-24 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("texts", "0001_initial"),
        ("comments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="text",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="texts.text",
            ),
        ),
    ]
