# Generated by Django 4.1.7 on 2023-05-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0005_alter_comment_photo_alter_comment_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="like",
            name="text",
        ),
        migrations.RemoveField(
            model_name="like",
            name="video",
        ),
        migrations.AddField(
            model_name="like",
            name="like",
            field=models.BooleanField(default=False),
        ),
    ]
