# Generated by Django 4.1.7 on 2023-05-08 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("texts", "0003_alter_text_tags"),
        (
            "comments",
            "0006_remove_like_photo_remove_like_text_remove_like_video_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="text",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="texts.text",
            ),
        ),
    ]
