# Generated by Django 4.1.7 on 2023-09-12 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0005_alter_photo_options"),
        ("comments", "0007_like_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="photos.photo",
            ),
        ),
    ]
