# Generated by Django 4.1.7 on 2023-09-18 10:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0009_bookmark"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookmark",
            old_name="like",
            new_name="bookmark",
        ),
    ]
