# Generated by Django 4.1.7 on 2023-05-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0002_alter_tag_name"),
        ("photos", "0003_alter_photo_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                default="",
                related_name="photos",
                to="tags.tag",
                verbose_name="태그",
            ),
        ),
    ]
