# Generated by Django 4.0.10 on 2023-10-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_alter_photo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.FileField(default='', max_length=300, null=True, upload_to='', verbose_name='사진파일'),
        ),
    ]
