# Generated by Django 4.0.10 on 2023-10-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_alter_photo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.FileField(default='', null=True, upload_to='photos/', verbose_name='사진파일'),
        ),
    ]
