# Generated by Django 4.0.10 on 2023-10-25 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_photo_image_url_alter_photo_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image_url',
        ),
    ]
