# Generated by Django 4.0.10 on 2023-10-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0013_remove_photo_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.URLField(default='', null=True, verbose_name='사진파일'),
        ),
    ]
