# Generated by Django 4.1.7 on 2023-03-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=30)),
            ],
            options={
                "verbose_name": "태그",
                "verbose_name_plural": "태그",
                "db_table": "tag",
            },
        ),
    ]
