# Generated by Django 4.1.7 on 2023-05-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0002_alter_tag_name"),
        ("texts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="text",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                default="",
                related_name="texts",
                to="tags.tag",
                verbose_name="태그",
            ),
        ),
    ]
