# Generated by Django 4.1.7 on 2023-06-14 10:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("texts", "0003_alter_text_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="text",
            options={"ordering": ["-created_at"]},
        ),
    ]
